package com.wallet.constant;

public enum  ErrorCode {

    PROCESSING(2),
    SUCCESS(1),
    EXCEPTION(0),
    // -1 -> -100 validate
    VALIDATE_FULL_NAME_INVALID(-1),
    VALIDATE_PIN_INVALID(-2),
    VALIDATE_PHONE_INVALID(-3),
    VALIDATE_PHONE_DUPLICATE(-4),
    VALIDATE_USER_ID_INVALID(-5),
    VALIDATE_AMOUNT_INVALID(-6),
    VALIDATE_TRANSACTION_ID_INVALID(-7),
    VALIDATE_TRANSACTION_DUPLICATE(-8),
    VALIDATE_BANK_CODE_INVALID(-9),
    VALIDATE_CAR_NUMBER_INVALID(-10),
    VALIDATE_CMND_INVALID(-11),
    VALIDATE_F6CARD_NO_INVALID(-12),
    VALIDATE_L4CARD_NO_INVALID(-13),
    VALIDATE_ORDER_ID_INVALID(-14),
    VALIDATE_SOURCE_OF_FUN_INVALID(-15),
    VALIDATE_SERVICE_TYPE_INVALID(-16),
    VALIDATE_CARD_TYPE_INVALID(-17),
    VALIDATE_USER_VERIFY_STATUS_INVALID(-18),
    VALIDATE_USER_VERIFY_COMMENT_INVALID(-19),
    VALIDATE_KEY_INVALID(-20),

    // -101 -> -200 BUS
    USER_PASSWORD_WRONG(-101),
    USER_PIN_WRONG(-102),
    BALANCE_NOT_ENOUGHT(-103),
    USER_HAS_NOT_MAPPING_YET(-104),
    DUPLICATE_TRANSACTION(-105),
    CHECK_BANK_NOT_SUPPORT(-106),
    CHECK_AMOUNT_LIMITATION(-107),
    CHECK_ORDER_NOT_FOUND_ON_CACHE(-108),
    CHECK_USER_DOES_NOT_EXIST(-109),
    CHECK_SERVICE_DOES_NOT_EXIST(-110),
    CALL_BACK_FAIL(-111),
    CHECK_CARD_NOT_AVALIBLE(-112),

    // -201 -> 300 VERIFY USER
    CHECK_VERIFY_USRER_PHONE_INVALID(-201),
    CHECK_VERIFY_USRER_ADDRESS_INVALID(-202),
    CHECK_VERIFY_USRER_DOB_INVALID(-203),
    CHECK_VERIFY_USRER_FULLNAME_INVALID(-204),
    CHECK_VERIFY_USRER_CMND_INVALID(-205),
    CHECK_VERIFY_USRER_PIN_INVALID(-206),
    CHECK_VERIFY_USRER_CMND_FRONT_IMG_INVALID(-207),
    CHECK_VERIFY_USRER_CMND_BACK_IMG_INVALID(-208),
    CHECK_VERIFY_USRER_AVATAR_IMG_INVALID(-209);

    private int value;
    ErrorCode(int value){
        this.value=value;
    }

    public int getValue() {
        return this.value;
    }
}